### ISSUE TITLE
Registration startup entered twice

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1080]
### Subject of the issue
The registration startup round is entered twice as observed in the logs:
```
[2022-07-14 11:00:47,658] [WARNING] [agent] The kwargs={'log_dir': '/logs'} passed to benchmark_tool have not been set!
[2022-07-14 11:00:47,779] [WARNING] [agent] The kwargs={'log_dir': '/benchmarks'} passed to benchmark_tool have not been set!
[2022-07-14 11:00:47,955] [INFO] [agent] Entered in the 'registration_startup' round for period 0
[2022-07-14 11:00:47,956] [INFO] [agent] Entered in the 'registration_startup' round for period 0
[2022-07-14 11:00:47,957] [INFO] [agent] Start processing messages...
[2022-07-14 11:00:47,958] [INFO] [agent] Entered in the 'registration_startup' behaviour
[2022-07-14 11:00:47,958] [INFO] [agent] Checking sync...
[2022-07-14 11:00:47,958] [INFO] [agent] Checking status @ http://localhost:26657/status
[2022-07-14 11:00:47,964] [INFO] [agent] Entered in the 'registration_startup' behaviour
```

This is probably related to the repeated transaction errors in our logs:
```
[2022-07-14 11:01:17,155] [ERROR] [agent] TransactionNotValidError: sender 0xAD56A50628D4915E841b7C2eCE13b33793b365d0 has already sent value for round: registration_startup
[2022-07-14 11:01:17,158] [ERROR] [agent] TransactionNotValidError: sender 0xAD56A50628D4915E841b7C2eCE13b33793b365d0 has already sent value for round: registration_startup
[2022-07-14 11:01:17,160] [ERROR] [agent] TransactionNotValidError: sender 0xAD56A50628D4915E841b7C2eCE13b33793b365d0 has already sent value for round: registration_startup
[2022-07-14 11:01:17,165] [ERROR] [agent] TransactionNotValidError: sender 0xAD56A50628D4915E841b7C2eCE13b33793b365d0 has already sent value for round: registration_startup
```

This is not a terminal error but is certainly worth addressing.

### Steps to reproduce
Run any e2e test.

### Expected behaviour
The registration round should be entered once.

### Actual behaviour
The registration round is entered twice.

**Comment by marcofavorito** [comment]
I discovered that the source of the problem is that in the more recent agent configurations there are at least two skills that: (1) are not abstract and (2) both include the `SharedState` model.

The valory skills that are not abstract atm are:
```
counter
apy_estimation_chained_abci
counter_client
hello_world_abci
liquidity_provision_abci
oracle_abci
register_reset_abci
registration_abci
simple_abci
test_abci
```

For example, consider the `oracle` agent. It has both the `registration_abci` and the `oracle_abci` skill, which are configured to load their own `SharedState`. During the set up phase, the `setup()` method of both `SharedState`s is called, which in turn calls `RoundSequence.setup` and then `AbciApp.setup` and `_schedule_round(self.initial_round_cls)`. 

A similar problem occurs in other agent configurations, e.g. agent  `apy_estimation_chained` uses both skills `apy_estimation_chained_abci` and `registration_abci`.

Ideas:
- either one of the two should be made abstract;
- make both abstract, and create an "entry-point" skill that takes care of the cconfiguration
- since `registration_abci` cannot be made abstract so easily

**Comment by marcofavorito** [comment]
I found out that the source of the problem is that in the more recent agent configurations there are at least two skills that: (1) are not abstract and (2) both include the `SharedState` model.

The valory skills that are not abstract atm are:
```
counter
apy_estimation_chained_abci
counter_client
hello_world_abci
liquidity_provision_abci
oracle_abci
register_reset_abci
registration_abci
simple_abci
test_abci
```

For example, consider the `oracle` agent. It has both the `registration_abci` and the `oracle_abci` skill, which are configured to load their own `SharedState`. During the set up phase, the `setup()` method of both `SharedState`s is called, which in turn calls `RoundSequence.setup` and then `AbciApp.setup` and `_schedule_round(self.initial_round_cls)`. Moreover, also the behaviour of `oracle_abci` is scheduled, which probably explains the issue mentioned above.

A similar problem occurs in other agent configurations, e.g. agent  `apy_estimation_chained` uses both skills `apy_estimation_chained_abci` and `registration_abci`.

Ideas:
- either one of the two should be made abstract;
- make both abstract, and create an "entry-point" skill that takes care of the configuration
- `registration_abci` cannot be made abstract so easily (it acts as the entrypoint for the behaviour `AgentRegistrationRoundBehaviour`). On the other hand, the other skill like `oracle_abci` uses the `SharedState.setup()` method to override the timeouts of the transition function:

```python
    def setup(self) -> None:
        """Set up."""
        super().setup()  # this causes the trouble since it calls RoundSequence.setup again
        OracleAbciApp.event_to_timeout[
            Event.ROUND_TIMEOUT
        ] = self.context.params.round_timeout_seconds
        OracleAbciApp.event_to_timeout[
            SafeEvent.ROUND_TIMEOUT
        ] = self.context.params.round_timeout_seconds
        OracleAbciApp.event_to_timeout[
            OracleEvent.ROUND_TIMEOUT
        ] = self.context.params.round_timeout_seconds
        OracleAbciApp.event_to_timeout[
            TSEvent.ROUND_TIMEOUT
        ] = self.context.params.round_timeout_seconds
        OracleAbciApp.event_to_timeout[
            ResetPauseEvent.ROUND_TIMEOUT
        ] = self.context.params.round_timeout_seconds
        OracleAbciApp.event_to_timeout[TSEvent.RESET_TIMEOUT] = (
            self.context.params.round_timeout_seconds * MULTIPLIER
        )
        OracleAbciApp.event_to_timeout[
            SafeEvent.VALIDATE_TIMEOUT
        ] = self.context.params.validate_timeout
        OracleAbciApp.event_to_timeout[
            OracleEvent.VALIDATE_TIMEOUT
        ] = self.context.params.validate_timeout
        OracleAbciApp.event_to_timeout[
            TSEvent.VALIDATE_TIMEOUT
        ] = self.context.params.validate_timeout
        OracleAbciApp.event_to_timeout[
            TSEvent.FINALIZE_TIMEOUT
        ] = self.context.params.finalize_timeout
        OracleAbciApp.event_to_timeout[
            TSEvent.CHECK_TIMEOUT
        ] = self.context.params.history_check_timeout
        OracleAbciApp.event_to_timeout[OracleEvent.DEPLOY_TIMEOUT] = (
            self.context.params.keeper_timeout + MARGIN
        )
        OracleAbciApp.event_to_timeout[SafeEvent.DEPLOY_TIMEOUT] = (
            self.context.params.keeper_timeout + MARGIN
        )
        OracleAbciApp.event_to_timeout[ResetPauseEvent.RESET_AND_PAUSE_TIMEOUT] = (
            self.context.params.observation_interval + MARGIN
        )

```

this code does not need to be in the setup method of SharedState since it does not change self/class attributes.

- remove the call to super().setup() (just a quick workaround...)

My suggestion is to make as much skill abstract as possible, and to use the "entry-point skill" approach. Why `registration_abci` should be special in this respect? It could be considered as an abstract skill that acts as a sub-module for more complex FSM and, incidentally, it can be chosen as the entry-point for the FSM by an non-abstract auxiliary skill, e.g. `oracle_entrypoint` skill.
