### ISSUE TITLE
Incorrect aea version used on deployment

### ISSUE THREAD

**Issue by Adamantios** [valory-xyz/open-autonomy#1399]
While using the `autonomy build-image` command, a previous version of `aea` was utilized instead of the one installed.
Witnessed this on the staging DO server with @8ball030 and @angrybayblade.

Needs investigation, this might have been an issue or incorrect use of the commands. The process followed was:

```bash
cd packages/valory/services/oracle_goerli
autonomy deploy build $DEPLOYMENT_KEYS --aev
autonomy build-image
```

**Comment by 8ball030** [comment]
This is caused by docker seeing it already has **a** latest image in its local cache. The fact that this is not the actual latest is irrelevant to docker as 

There are 3 options here;
Either a) pull the latest open-aea version temp local fix
B) modify the autonomy build-image command so it passes the flag
pull-parents. This will force the docker engine to ensure that the latest  image in cache matches the latest in dockerhub
C) in the image dockerfile, we reference latest image, we could change that to the correct tag.
